const STORE='rouan-dojo-attempts-v3';
const WEAK_STORE='rouan-dojo-manual-weak-v1';
const state={data:null,attempts:[],manualWeak:new Set(),screen:'home',subject:'industrial_general',mode:'past',year:'all',index:0,selected:null,revealed:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function loadAttempts(){return loadJson(STORE,[])}
function loadManualWeak(){return new Set(loadJson(WEAK_STORE,[]))}
function save(){localStorage.setItem(STORE,JSON.stringify(state.attempts));localStorage.setItem(WEAK_STORE,JSON.stringify([...state.manualWeak]))}
function qs(){return state.data.QUESTIONS}
function statsFor(id){const a=state.attempts.filter(x=>x.questionId===id).sort((x,y)=>x.answeredAt.localeCompare(y.answeredAt));const correct=a.filter(x=>x.correct).length;let cw=0,cc=0;for(let i=a.length-1;i>=0;i--){if(a[i].correct)break;cw++}for(let i=a.length-1;i>=0;i--){if(!a[i].correct)break;cc++}return{n:a.length,accuracy:a.length?Math.round(correct/a.length*100):null,cw,cc}}
function weak(id){if(state.manualWeak.has(id))return true;const s=statsFor(id);if(s.cc>=3)return false;if(s.cw>=2)return true;return s.n>=3&&(s.accuracy??100)<70}
function recentAccuracy(subject=null,limit=20){let rows=state.attempts;if(subject){const ids=new Set(qs().filter(q=>q.subject===subject).map(q=>q.id));rows=rows.filter(a=>ids.has(a.questionId))}rows=rows.slice(-limit);return rows.length?Math.round(rows.filter(a=>a.correct).length/rows.length*100):null}
function progress(subject){const all=qs().filter(q=>q.subject===subject),ids=new Set(all.map(q=>q.id)),rows=state.attempts.filter(a=>ids.has(a.questionId)),answered=new Set(rows.map(a=>a.questionId));const past=all.filter(q=>q.kind==='past'),pred=all.filter(q=>q.kind==='prediction');const pastIds=new Set(past.map(q=>q.id)),predIds=new Set(pred.map(q=>q.id));const pastAnswered=new Set(rows.filter(a=>pastIds.has(a.questionId)).map(a=>a.questionId)).size,predAnswered=new Set(rows.filter(a=>predIds.has(a.questionId)).map(a=>a.questionId)).size;return{total:all.length,answered:answered.size,progress:all.length?Math.round(answered.size/all.length*100):0,accuracy:rows.length?Math.round(rows.filter(a=>a.correct).length/rows.length*100):null,recent:recentAccuracy(subject),weak:all.filter(q=>weak(q.id)).length,pastTotal:past.length,pastAnswered,predTotal:pred.length,predAnswered}}
function yearProgress(subject,year){const all=qs().filter(q=>q.subject===subject&&q.kind==='past'&&q.yearLabel===year),ids=new Set(all.map(q=>q.id)),rows=state.attempts.filter(a=>ids.has(a.questionId)),answered=new Set(rows.map(a=>a.questionId));return{total:all.length,answered:answered.size,pct:all.length?Math.round(answered.size/all.length*100):0,accuracy:rows.length?Math.round(rows.filter(a=>a.correct).length/rows.length*100):null}}
function overall(){const ans=new Set(state.attempts.map(a=>a.questionId));return{total:qs().length,answered:ans.size,progress:qs().length?Math.round(ans.size/qs().length*100):0,accuracy:state.attempts.length?Math.round(state.attempts.filter(a=>a.correct).length/state.attempts.length*100):null,recent:recentAccuracy(),weak:qs().filter(q=>weak(q.id)).length}}
function yearsFor(subject){return [...new Set(qs().filter(q=>q.subject===subject&&q.kind==='past').map(q=>q.yearLabel).filter(Boolean))].sort((a,b)=>b.localeCompare(a,'ja'))}
function currentSet(){let a=qs().filter(q=>q.subject===state.subject);if(state.mode==='weak')a=a.filter(q=>weak(q.id));else a=a.filter(q=>q.kind===state.mode);if(state.mode==='past'&&state.year!=='all')a=a.filter(q=>q.yearLabel===state.year);return a}
function nav(){return `<nav class="bottom"><div class="navinner">${[['home','⌂','ホーム'],['quiz','✓','問題'],['weak','↺','苦手'],['settings','⚙','設定']].map(([s,i,l])=>`<button class="navbtn ${state.screen===s?'active':''}" data-nav="${s}"><span>${i}</span><small>${l}</small></button>`).join('')}</div></nav>`}
function head(){const o=overall();return `<header class="top"><div><div class="eyebrow">労働安全コンサルタント試験対策</div><h1>労働安全コンサル道場</h1></div><div class="overall"><strong>${o.progress}%</strong><small>全体進捗</small></div></header>`}
function home(){const o=overall();return `<section class="content"><div class="hero"><div><div class="eyebrow">学習状況</div><div class="big">${o.answered}<span> / ${o.total}問</span></div><div class="mini">一度以上解答・自己採点した問題</div></div><div class="stats"><div class="accuracy-stats"><div class="stat"><span>直近20回の正答率</span><b>${o.recent??'—'}${o.recent!==null?'%':''}</b></div><div class="stat"><span>累積の正答率</span><b>${o.accuracy??'—'}${o.accuracy!==null?'%':''}</b></div></div><div class="stat weak-stat"><span>苦手問題</span><b>${o.weak}問</b></div></div></div><div class="section-title"><h2>科目別進捗</h2><p>年度別の進捗も自動集計します。</p></div><div class="grid">${state.data.SUBJECTS.map(s=>subjectCard(s)).join('')}</div><div class="notice"><strong>苦手問題の自動判定</strong><p>2回連続不正解、または3回以上回答して正答率70%未満で自動ストック。手動で「苦手」に固定することもできます。3回連続正解すると自動判定分は克服扱いになります。</p></div></section>`}
function subjectCard(s){const p=progress(s.id);const years=yearsFor(s.id);return `<article class="card"><div class="cardhead"><div><h3>${esc(s.label)}</h3><p>${esc(s.description)}</p></div><div class="pct">${p.progress}%</div></div><div class="bar"><span style="width:${p.progress}%"></span></div><div class="metrics"><div>解答済み<b>${p.answered}/${p.total}</b></div><div>正答率<b>${p.accuracy??'—'}${p.accuracy!==null?'%':''}</b></div><div>苦手<b>${p.weak}</b></div></div><div class="split"><span>過去問 ${p.pastAnswered}/${p.pastTotal}</span><span>予想 ${p.predAnswered}/${p.predTotal}</span></div>${years.length?`<div class="yearprogress">${years.map(y=>{const yp=yearProgress(s.id,y);return `<button class="yearrow" data-startyear="${s.id}:${y}"><span>${esc(y)}</span><span>${yp.answered}/${yp.total}・${yp.pct}%${yp.accuracy!==null?`・正答${yp.accuracy}%`:''}</span></button>`}).join('')}</div>`:''}<div class="buttons" style="margin-top:12px"><button class="primary" data-start="${s.id}:past">過去問</button><button class="secondary" data-start="${s.id}:prediction">予想</button><button class="secondary" data-start="${s.id}:weak">苦手</button></div></article>`}
function toolbar(){const years=yearsFor(state.subject);return `<div class="toolbar"><select id="subjectSel">${state.data.SUBJECTS.map(s=>`<option value="${s.id}" ${s.id===state.subject?'selected':''}>${esc(s.label)}</option>`).join('')}</select><div class="segment">${[['past','過去問'],['prediction','予想'],['weak','苦手']].map(([m,l])=>`<button data-mode="${m}" class="${state.mode===m?'active':''}">${l}</button>`).join('')}</div>${state.mode==='past'&&years.length?`<select id="yearSel"><option value="all">全年度</option>${years.map(y=>`<option value="${esc(y)}" ${state.year===y?'selected':''}>${esc(y)}</option>`).join('')}</select>`:''}</div>`}
function promptHtml(q){return `<p class="prompt">${esc(q.prompt)}</p>${q.figurePending?`<div class="figure-note">図表を含む問題です。図表のアプリ内表示は整備中です。</div>`:''}`}
function quiz(){const set=currentSet();if(!set.length)return `<section class="content">${toolbar()}<div class="qcard empty"><h2>この条件の問題はまだありません</h2><p class="mini">別の年度・科目を選択してください。</p></div></section>`;const q=set[state.index%set.length],s=statsFor(q.id);const essay=q.questionType==='essay'||!(q.choices||[]).length;let body='';if(!essay){body=`<div class="choices">${q.choices.map((c,i)=>{let cl='choice';if(state.revealed&&i===q.correctIndex)cl+=' correct';if(state.revealed&&i===state.selected&&i!==q.correctIndex)cl+=' wrong';return `<button class="${cl}" data-choice="${i}" ${state.revealed?'disabled':''}><span class="idx">${i+1}</span><span>${esc(c)}</span></button>`}).join('')}</div>`}else if(!state.revealed){body=`<div class="buttons"><button class="primary" data-reveal-essay>解答・採点ポイントを見る</button></div>`}return `<section class="content">${toolbar()}<article class="qcard"><div class="qmeta"><span class="badge ${q.kind==='prediction'?'pred':''}">${q.kind==='past'?'過去問':'予想問題'}</span><span>${esc(q.yearLabel||'予想')} ${q.questionNo?`問${q.questionNo}`:''}</span><span>${state.index%set.length+1}/${set.length}</span>${q.lawAsOf?`<span>法令基準 ${esc(q.lawAsOf)}</span>`:''}</div><div class="qtitle-row"><h2>${esc(q.title)}</h2><button class="weakpin ${state.manualWeak.has(q.id)?'on':''}" data-toggle-weak="${q.id}">${state.manualWeak.has(q.id)?'★ 苦手':'☆ 苦手登録'}</button></div>${promptHtml(q)}${body}${state.revealed?result(q,s):''}</article></section>`}
function result(q,s){const essay=q.questionType==='essay'||!(q.choices||[]).length;if(essay){return `<div class="result"><h3>記述式・自己採点</h3><div class="explain"><strong>${q.explanationPending?'模範解答（整備中）':'模範解答・解説'}</strong><div>${esc(q.explanation)}</div></div><div class="explain"><strong>答案作成ポイント</strong><ul>${(q.points||[]).map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div>${q.legalReferences?.length?refs(q):''}<div class="selfgrade"><span>今回の出来を記録</span><button class="primary" data-selfgrade="1">できた</button><button class="danger" data-selfgrade="0">要復習</button></div><div class="nextrow"><span class="mini">自己採点: ${s.n}回 / 到達率 ${s.accuracy??'—'}${s.accuracy!==null?'%':''}</span><button class="secondary" data-next>次の問題へ</button></div></div>`}
const correct=state.selected===q.correctIndex;return `<div class="result"><h3 class="${correct?'ok':'ng'}">${correct?'✓ 正解':'✕ 不正解'}　正解：${q.correctIndex+1}</h3>${q.sourceAnswerVerified?`<div class="source-ok">正答は原問題の〇印で確認済み</div>`:''}<div class="explain"><strong>${q.explanationPending?'解説（整備中）':'解説'}</strong><div>${esc(q.explanation)}</div></div>${q.choiceNotes?.length?`<ul class="notes">${q.choiceNotes.map((n,i)=>`<li><b>${i+1}</b> ${esc(n)}</li>`).join('')}</ul>`:''}<div class="explain"><strong>学習ポイント</strong><ul>${(q.points||[]).map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div>${q.legalReferences?.length?refs(q):''}<div class="nextrow"><span class="mini">この問題: ${s.n}回 / 正答率 ${s.accuracy??'—'}${s.accuracy!==null?'%':''}</span><button class="primary" data-next>次の問題へ</button></div></div>`}
function refs(q){return `<div class="refs"><h4>根拠法令・指針</h4><ul>${q.legalReferences.map(r=>`<li><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.label)}</a>${r.detail?` — ${esc(r.detail)}`:''}</li>`).join('')}</ul></div>`}
function settings(){const st=state.data.IMPORT_STATUS||{};return `<section class="content"><div class="settings"><h2>設定・バックアップ</h2><div class="setting-row"><div><b>問題データ</b><div class="mini">データ版 ${esc(state.data.DATA_VERSION||'—')} / ${qs().length}問</div>${Object.values(st).map(x=>`<div class="mini">・${esc(x)}</div>`).join('')}</div></div><div class="setting-row"><div><b>学習データをバックアップ</b><div class="mini">回答履歴と手動苦手登録をJSONファイルとして保存します。</div></div><button class="secondary" id="backup">書き出す</button></div><div class="setting-row"><div><b>バックアップから復元</b><div class="mini">別端末への移行や復元に使えます。</div></div><input class="fileinput" type="file" id="restore" accept="application/json,.json"></div><div class="setting-row"><div><b>学習履歴を消去</b><div class="mini">端末内の回答履歴・苦手登録をすべて削除します。</div></div><button class="danger" id="clear">消去</button></div><div class="setting-row"><div><b>保存方式</b><div class="mini">学習履歴はこの端末のlocalStorageに保存。サーバーへは送信しません。</div></div></div></div></section>`}
function render(){let main=state.screen==='home'?home():state.screen==='settings'?settings():quiz();document.querySelector('#app').innerHTML=`<main class="shell">${head()}${main}${nav()}</main>`;bind()}
function resetQuiz(){state.index=0;state.selected=null;state.revealed=false}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.nav;if(state.screen==='weak')state.mode='weak';resetQuiz();render()});document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{[state.subject,state.mode]=b.dataset.start.split(':');state.year='all';state.screen=state.mode==='weak'?'weak':'quiz';resetQuiz();render()});document.querySelectorAll('[data-startyear]').forEach(b=>b.onclick=()=>{[state.subject,state.year]=b.dataset.startyear.split(':');state.mode='past';state.screen='quiz';resetQuiz();render()});document.querySelector('#subjectSel')?.addEventListener('change',e=>{state.subject=e.target.value;state.year='all';resetQuiz();render()});document.querySelector('#yearSel')?.addEventListener('change',e=>{state.year=e.target.value;resetQuiz();render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.year='all';state.screen=state.mode==='weak'?'weak':'quiz';resetQuiz();render()});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.choice)));document.querySelector('[data-reveal-essay]')?.addEventListener('click',()=>{state.revealed=true;render()});document.querySelectorAll('[data-selfgrade]').forEach(b=>b.onclick=()=>selfGrade(b.dataset.selfgrade==='1'));document.querySelector('[data-next]')?.addEventListener('click',()=>{state.index++;state.selected=null;state.revealed=false;render()});document.querySelector('[data-toggle-weak]')?.addEventListener('click',e=>{const id=e.currentTarget.dataset.toggleWeak;if(state.manualWeak.has(id))state.manualWeak.delete(id);else state.manualWeak.add(id);save();render()});document.querySelector('#backup')?.addEventListener('click',backup);document.querySelector('#restore')?.addEventListener('change',restore);document.querySelector('#clear')?.addEventListener('click',()=>{if(confirm('学習履歴と苦手登録をすべて消去しますか？')){state.attempts=[];state.manualWeak.clear();save();render()}})}
function answer(i){const q=currentSet()[state.index%currentSet().length];state.selected=i;state.revealed=true;state.attempts.push({id:crypto.randomUUID?.()||String(Date.now()),questionId:q.id,selectedIndex:i,correct:i===q.correctIndex,answeredAt:new Date().toISOString(),assessmentType:'choice'});save();render()}
function selfGrade(ok){const q=currentSet()[state.index%currentSet().length];state.attempts.push({id:crypto.randomUUID?.()||String(Date.now()),questionId:q.id,selectedIndex:ok?1:0,correct:ok,answeredAt:new Date().toISOString(),assessmentType:'self'});save();state.index++;state.selected=null;state.revealed=false;render()}
function backup(){const blob=new Blob([JSON.stringify({version:3,exportedAt:new Date().toISOString(),attempts:state.attempts,manualWeak:[...state.manualWeak]},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rouan-dojo-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function restore(e){const f=e.target.files?.[0];if(!f)return;try{const j=JSON.parse(await f.text()),rows=Array.isArray(j)?j:j.attempts;if(!Array.isArray(rows))throw 0;state.attempts=rows;state.manualWeak=new Set(Array.isArray(j.manualWeak)?j.manualWeak:[]);save();alert('復元しました。');render()}catch{alert('バックアップファイルを読み込めませんでした。')}}
(async()=>{state.attempts=loadAttempts();state.manualWeak=loadManualWeak();const base=await fetch('./questions.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()});let idx={files:[]};try{idx=await fetch('./data/index.json',{cache:'no-store'}).then(r=>r.ok?r.json():{files:[]})}catch{}const extras=[];for(const url of (idx.files||[])){try{const d=await fetch(url,{cache:'no-store'}).then(r=>r.json());extras.push(...(d.QUESTIONS||[]))}catch(e){console.warn('追加データを読み込めませんでした',url,e)}}state.data={...base,DATA_VERSION:idx.DATA_VERSION||base.DATA_VERSION,IMPORT_STATUS:idx.IMPORT_STATUS||{},QUESTIONS:[...(base.QUESTIONS||[]),...extras]};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})().catch(e=>{document.querySelector('#app').textContent='アプリの読み込みに失敗しました。'+e});
