const STORE='rouan-dojo-attempts-v2';
const state={data:null,attempts:[],screen:'home',subject:'industrial_general',mode:'past',index:0,selected:null,revealed:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadAttempts(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
function save(){localStorage.setItem(STORE,JSON.stringify(state.attempts))}
function qs(){return state.data.QUESTIONS}
function statsFor(id){const a=state.attempts.filter(x=>x.questionId===id).sort((x,y)=>x.answeredAt.localeCompare(y.answeredAt));const correct=a.filter(x=>x.correct).length;let cw=0,cc=0;for(let i=a.length-1;i>=0;i--){if(a[i].correct)break;cw++}for(let i=a.length-1;i>=0;i--){if(!a[i].correct)break;cc++}return{n:a.length,accuracy:a.length?Math.round(correct/a.length*100):null,cw,cc}}
function weak(id){const s=statsFor(id);if(s.cc>=3)return false;if(s.cw>=2)return true;return s.n>=3&&(s.accuracy??100)<70}
function progress(subject){const all=qs().filter(q=>q.subject===subject),ids=new Set(all.map(q=>q.id)),rows=state.attempts.filter(a=>ids.has(a.questionId)),answered=new Set(rows.map(a=>a.questionId));const past=all.filter(q=>q.kind==='past'),pred=all.filter(q=>q.kind==='prediction');const pastAnswered=new Set(rows.filter(a=>past.some(q=>q.id===a.questionId)).map(a=>a.questionId)).size,predAnswered=new Set(rows.filter(a=>pred.some(q=>q.id===a.questionId)).map(a=>a.questionId)).size;return{total:all.length,answered:answered.size,progress:all.length?Math.round(answered.size/all.length*100):0,accuracy:rows.length?Math.round(rows.filter(a=>a.correct).length/rows.length*100):null,weak:all.filter(q=>weak(q.id)).length,pastTotal:past.length,pastAnswered,predTotal:pred.length,predAnswered}}
function overall(){const ans=new Set(state.attempts.map(a=>a.questionId));return{total:qs().length,answered:ans.size,progress:qs().length?Math.round(ans.size/qs().length*100):0,accuracy:state.attempts.length?Math.round(state.attempts.filter(a=>a.correct).length/state.attempts.length*100):null,weak:qs().filter(q=>weak(q.id)).length}}
function currentSet(){let a=qs().filter(q=>q.subject===state.subject);if(state.mode==='weak')a=a.filter(q=>weak(q.id));else a=a.filter(q=>q.kind===state.mode);return a}
function nav(){return `<nav class="bottom"><div class="navinner">${[['home','⌂','ホーム'],['quiz','✓','問題'],['weak','↺','苦手'],['settings','⚙','設定']].map(([s,i,l])=>`<button class="navbtn ${state.screen===s?'active':''}" data-nav="${s}"><span>${i}</span><small>${l}</small></button>`).join('')}</div></nav>`}
function head(){const o=overall();return `<header class="top"><div><div class="eyebrow">労働安全コンサルタント試験対策</div><h1>労働安全コンサル道場</h1></div><div class="overall"><strong>${o.progress}%</strong><small>全体進捗</small></div></header>`}
function home(){const o=overall();return `<section class="content"><div class="hero"><div><div class="eyebrow">学習状況</div><div class="big">${o.answered}<span> / ${o.total}問</span></div><div class="mini">一度以上解答した問題</div></div><div class="stats"><div class="stat"><span>総合正答率</span><b>${o.accuracy??'—'}${o.accuracy!==null?'%':''}</b></div><div class="stat"><span>総回答数</span><b>${state.attempts.length}回</b></div><div class="stat"><span>苦手問題</span><b>${o.weak}問</b></div></div></div><div class="section-title"><h2>科目別進捗</h2><p>過去問・予想問題・苦手問題を科目ごとに管理します。</p></div><div class="grid">${state.data.SUBJECTS.map(s=>subjectCard(s)).join('')}</div><div class="notice"><strong>苦手問題の自動判定</strong><p>2回連続不正解、または3回以上回答して正答率70%未満で自動ストック。3回連続正解すると克服扱いになります。</p></div></section>`}
function subjectCard(s){const p=progress(s.id);const years=[...new Set(qs().filter(q=>q.subject===s.id&&q.kind==='past').map(q=>q.yearLabel).filter(Boolean))];return `<article class="card"><div class="cardhead"><div><h3>${esc(s.label)}</h3><p>${esc(s.description)}</p></div><div class="pct">${p.progress}%</div></div><div class="bar"><span style="width:${p.progress}%"></span></div><div class="metrics"><div>解答済み<b>${p.answered}/${p.total}</b></div><div>正答率<b>${p.accuracy??'—'}${p.accuracy!==null?'%':''}</b></div><div>苦手<b>${p.weak}</b></div></div><div class="split"><span>過去問 ${p.pastAnswered}/${p.pastTotal}</span><span>予想 ${p.predAnswered}/${p.predTotal}</span></div>${years.length?`<div class="yearlist">${years.map(y=>`<span class="yearpill">${esc(y)}</span>`).join('')}</div>`:''}<div class="buttons" style="margin-top:12px"><button class="primary" data-start="${s.id}:past">過去問</button><button class="secondary" data-start="${s.id}:prediction">予想</button><button class="secondary" data-start="${s.id}:weak">苦手</button></div></article>`}
function toolbar(){return `<div class="toolbar"><select id="subjectSel">${state.data.SUBJECTS.map(s=>`<option value="${s.id}" ${s.id===state.subject?'selected':''}>${esc(s.label)}</option>`).join('')}</select><div class="segment">${[['past','過去問'],['prediction','予想'],['weak','苦手']].map(([m,l])=>`<button data-mode="${m}" class="${state.mode===m?'active':''}">${l}</button>`).join('')}</div></div>`}
function quiz(){const set=currentSet();if(!set.length)return `<section class="content">${toolbar()}<div class="qcard empty"><h2>この条件の問題はまだありません</h2><p class="mini">問題データを追加するとここに表示されます。</p></div></section>`;const q=set[state.index%set.length],s=statsFor(q.id);const choices=q.choices||[];let body='';if(choices.length){body=`<div class="choices">${choices.map((c,i)=>{let cl='choice';if(state.revealed&&i===q.correctIndex)cl+=' correct';if(state.revealed&&i===state.selected&&i!==q.correctIndex)cl+=' wrong';return `<button class="${cl}" data-choice="${i}" ${state.revealed?'disabled':''}><span class="idx">${i+1}</span><span>${esc(c)}</span></button>`}).join('')}</div>`}else{body=`<div class="buttons"><button class="primary" data-reveal-essay>解答・採点ポイントを見る</button></div>`}return `<section class="content">${toolbar()}<article class="qcard"><div class="qmeta"><span class="badge ${q.kind==='prediction'?'pred':''}">${q.kind==='past'?'過去問':'予想問題'}</span><span>${esc(q.yearLabel||'予想')} ${q.questionNo?`問${q.questionNo}`:''}</span><span>${state.index%set.length+1}/${set.length}</span></div><h2>${esc(q.title)}</h2><p class="prompt">${esc(q.prompt)}</p>${body}${state.revealed?result(q,s):''}</article></section>`}
function result(q,s){const correct=state.selected===q.correctIndex;return `<div class="result"><h3 class="${correct?'ok':'ng'}">${correct?'✓ 正解':'✕ 不正解'}${q.choices?.length?`　正解：${q.correctIndex+1}`:''}</h3><div class="explain"><strong>解説</strong><div>${esc(q.explanation)}</div></div>${q.choiceNotes?.length?`<ul class="notes">${q.choiceNotes.map((n,i)=>`<li><b>${i+1}</b> ${esc(n)}</li>`).join('')}</ul>`:''}<div class="explain"><strong>学習ポイント</strong><ul>${(q.points||[]).map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div>${q.legalReferences?.length?`<div class="refs"><h4>根拠法令・指針</h4><ul>${q.legalReferences.map(r=>`<li><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.label)}</a>${r.detail?` — ${esc(r.detail)}`:''}</li>`).join('')}</ul></div>`:''}<div class="nextrow"><span class="mini">この問題: ${s.n}回 / 正答率 ${s.accuracy??'—'}${s.accuracy!==null?'%':''}</span><button class="primary" data-next>次の問題へ</button></div></div>`}
function settings(){return `<section class="content"><div class="settings"><h2>設定・バックアップ</h2><div class="setting-row"><div><b>学習データをバックアップ</b><div class="mini">回答履歴をJSONファイルとして保存します。</div></div><button class="secondary" id="backup">書き出す</button></div><div class="setting-row"><div><b>バックアップから復元</b><div class="mini">別端末への移行や復元に使えます。</div></div><input class="fileinput" type="file" id="restore" accept="application/json,.json"></div><div class="setting-row"><div><b>学習履歴を消去</b><div class="mini">端末内の回答履歴をすべて削除します。</div></div><button class="danger" id="clear">消去</button></div><div class="setting-row"><div><b>保存方式</b><div class="mini">学習履歴はこの端末のlocalStorageに保存。サーバーへは送信しません。</div></div></div></div></section>`}
function render(){let main=state.screen==='home'?home():state.screen==='settings'?settings():quiz();document.querySelector('#app').innerHTML=`<main class="shell">${head()}${main}${nav()}</main>`;bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.nav;state.mode=state.screen==='weak'?'weak':state.mode;state.index=0;state.revealed=false;render()});document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{[state.subject,state.mode]=b.dataset.start.split(':');state.screen=state.mode==='weak'?'weak':'quiz';state.index=0;state.revealed=false;render()});document.querySelector('#subjectSel')?.addEventListener('change',e=>{state.subject=e.target.value;state.index=0;state.revealed=false;render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.screen=state.mode==='weak'?'weak':'quiz';state.index=0;state.revealed=false;render()});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.choice)));document.querySelector('[data-next]')?.addEventListener('click',()=>{state.index++;state.selected=null;state.revealed=false;render()});document.querySelector('#backup')?.addEventListener('click',backup);document.querySelector('#restore')?.addEventListener('change',restore);document.querySelector('#clear')?.addEventListener('click',()=>{if(confirm('学習履歴をすべて消去しますか？')){state.attempts=[];save();render()}})}
function answer(i){const set=currentSet(),q=set[state.index%set.length];state.selected=i;state.revealed=true;state.attempts.push({id:crypto.randomUUID?.()||String(Date.now()),questionId:q.id,selectedIndex:i,correct:i===q.correctIndex,answeredAt:new Date().toISOString()});save();render()}
function backup(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),attempts:state.attempts},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rouan-dojo-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function restore(e){const f=e.target.files?.[0];if(!f)return;try{const j=JSON.parse(await f.text()),rows=Array.isArray(j)?j:j.attempts;if(!Array.isArray(rows))throw 0;state.attempts=rows;save();alert('復元しました。');render()}catch{alert('バックアップファイルを読み込めませんでした。')}}
(async()=>{state.attempts=loadAttempts();state.data=await fetch('./questions.json',{cache:'no-store'}).then(r=>r.json());render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})().catch(e=>{document.querySelector('#app').textContent='アプリの読み込みに失敗しました。'+e});
